### ISSUE TITLE
No errors shown for using non-existent table in stored procedures.

### ISSUE THREAD

**Issue by Shiwatari** [pgcodekeeper/pgcodekeeper#99]
During build, it doesn't cause any warnings or errors if non-existent tables are referenced in a stored procedure.
Is this a known issue, or is there a fix planned for it by any chance?

**Comment by AXEPOH** [comment]
This is expected behavior: link checking is done by the user. We just check the syntax and look for dependencies.

Maybe sometime in the future...

**Comment by Shiwatari** [comment]
i see. Thank you.
In that case, wouldn't the stored procedure be dependent on a table that doesn't exist? 
Also, which dependencies do you mean that is being checked? 
I was checking, and in table creation scripts if an index is created on a non-existent table then it throws an error, but if a foreign key references a non-existent table then it doesn't show any errors.

**Comment by AXEPOH** [comment]
Technically yes, but it won't have any effect.
Dependencies child->parent are checked more strictly, as it is important for the correct construction of objects tree in the project. In other expressions, we collect only references to objects, since we do not always have enough context to determine the existence of an object (for example, system objects or extension objects).
